[redis_cluster]
redis-node-1 ansible_host=localhost ansible_port=2222 ansible_user=root internal_ip=10.10.0.11
redis-node-2 ansible_host=localhost ansible_port=2223 ansible_user=root internal_ip=10.10.0.12
redis-node-3 ansible_host=localhost ansible_port=2224 ansible_user=root internal_ip=10.10.0.13
redis-node-4 ansible_host=localhost ansible_port=2225 ansible_user=root internal_ip=10.10.0.14
redis-node-5 ansible_host=localhost ansible_port=2226 ansible_user=root internal_ip=10.10.0.15
redis-node-6 ansible_host=localhost ansible_port=2227 ansible_user=root internal_ip=10.10.0.16