---
- name: Trigger Redis Cluster Failover
  hosts: all
  gather_facts: false
  tasks:
    - name: Execute cluster failover command
      command: redis-cli -p {{ target_replica_port }} cluster failover
      when: internal_ip == target_replica_ip

